name: chex
channels:
  - conda-forge  # 优先使用conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pytorch=2.0.1
  - torchvision=0.15
  - torchmetrics=0.11
  - timm
  - matplotlib
  - pandas
  - tqdm
  - mkl
  - pip:
    - transformers==4.37
    - tokenizers==0.15
    - hydra-core==1.3
    - omegaconf
    - albumentations==1.3
    - pydicom
    - ftfy
    - deepdiff